{
	"Select Language": "Select Language",
	"English": "English",
	"Bitcoin Teller Machine": "Bitcoin Teller Machine",
	"START": "START",
	"Identity": "Identity",
	"Wallet": "Wallet",
	"Bitcoins": "Bitcoins",
	"Disclaimer": "Disclaimer",
	"I accept these terms and conditions.": "I accept these terms and conditions.",
	"Cancel": "Cancel",
	"Identity Verification": "Identity Verification",
	"Wallet Info": "Wallet Info",
	"Enter your Mobile Number": "Enter your Mobile Number",
	"Please enter your mobile number to verify your identity": "Please enter your mobile number to verify your identity",
	"Proceed": "Proceed",
	"We're very sorry, the machine is temporarily out of service.": "We're very sorry, the machine is temporarily out of service.",
	"Close": "Close",
	"Buy Bitcoins": "Buy Bitcoins",
	"Enter Verification Code": "Enter Verification Code",
	"Please enter the 6-Digit verification code sent to your mobile": "Please enter the 6-Digit verification code sent to your mobile",
	"Please select one of the following options": "Please select one of the following options",
	"Current Transaction Limit ": "Current Transaction Limit ",
	"Buy": "Buy",
	"Sell": "Sell",
	"Redeem": "Redeem",
	"Code": "Code",
	"Verify": "Verify",
	"Refund": "Refund",
	"Refill Note Recycler": "Refill Note Recycler",
	"Do you have a Bitcoin Wallet?": "Do you have a Bitcoin Wallet?",
	"Kindly please have the QR Code of your Bitcoin Wallet": "Kindly please have the QR Code of your Bitcoin Wallet",
	"Yes": "Yes",
	"No": "No",
	"Wallet Scan": "Wallet Scan",
	"Make sure that your entire QR Code is visible on the screen below": "Make sure that your entire QR Code is visible on the screen below",
	"Back": "Back",
	"Your Wallet is Printing": "Your Wallet is Printing",
	"Please collect your paper wallet from the tray below": "Please collect your paper wallet from the tray below",
	"ID Document": "ID Document",
	"Face Scan": "Face Scan",
	"Please Select your Type of ID": "Please Select your Type of ID",
	"Only accepted forms of ID are listed.": "Only accepted forms of ID are listed.",
	"ID Card": "ID Card",
	"Passport": "Passport",
	"Capture": "Capture",
	"Confirm ID Card Scan": "Confirm ID Card Scan",
	"Click confirm if this photo is clear and focused": "Click confirm if this photo is clear and focused",
	"Scan Again": "Scan Again",
	"Confrim": "Confrim",
	"Confirm Photo": "Confirm Photo",
	"Please confirm that your face is fully visible in this photo": "Please confirm that your face is fully visible in this photo",
	"Take Again": "Take Again",
	"Transaction Limit": "Transaction Limit",
	"Insert Cash": "Insert Cash",
	"banknotes only": "banknotes only",
	"Total": "Total",
	"Wallet Address": "Wallet Address",
	"I'm Done": "I'm Done",
	"Please Wait": "Please Wait",
	"Coins are Being Sent": "Coins are Being Sent",
	"Top up successful": "Top up successful",
	"received and": "received and",
	"has been sent to": "has been sent to",
	"It may take an hour for the coins to show up on your wallet.": "It may take an hour for the coins to show up on your wallet.",
	"Print Receipt": "Print Receipt",
	"Deposit Coins": "Deposit Coins",
	"Redeem Code": "Redeem Code",
	"Withdrawals above ": "Withdrawals above ",
	"will require additional confirmation.": "will require additional confirmation.",
	"You will receive an SMS when your transaction has been verified.": "You will receive an SMS when your transaction has been verified.",
	"Approx.": "Approx.",
	"Select the amount you would like to withdraw": "Select the amount you would like to withdraw",
	"The exact amount you requested is not currently available.": "The exact amount you requested is not currently available.",
	"You have ": "You have ",
	"Receive Cash": "Receive Cash",
	"Scan QR Code Now": "Scan QR Code Now",
	"Send Bitcoins": "Send Bitcoins",
	"Scan with your wallet app.": "Scan with your wallet app.",
	"Send exactly": "Send exactly",
	"Always include a transaction fee.": "Always include a transaction fee.",
	"Mobile Verification": "Mobile Verification",
	"Deposit coins": "Deposit coins",
	"Collect Cash": "Collect Cash",
	"Please collect your cash from the tray below": "Please collect your cash from the tray below",
	"Requested": "Requested",
	"Dispensed": "Dispensed",
	"Remaining": "Remaining",
	"Withdrawal successful": "Withdrawal successful",
	" sold and ": " sold and ",
	" dispensed.": " dispensed.",
	"Pending": "Pending",
	" will be dispensed.": " will be dispensed.",
	"Transactions above ": "Transactions above ",
	" require additional time to verify. This usually takes": " require additional time to verify. This usually takes",
	" minutes.": " minutes.",
	"You will receive an SMS shortly, please return to the machine at that time.": "You will receive an SMS shortly, please return to the machine at that time.",
	"Refill Complete": "Refill Complete",
	" inserted into cash recycler": " inserted into cash recycler",
	"Refund Code": "Refund Code",
	"Receive Bitcoins": "Receive Bitcoins",
	"Enter Refund Code": "Enter Refund Code",
	"Please enter the 8-Digit refund code sent to your mobile.": "Please enter the 8-Digit refund code sent to your mobile.",
	"Continue": "Continue",
	"Refund Complete": "Refund Complete",
	"Thank you": "Thank you",
	"We appreciate your patronage. We look forward to your next transaction.": "We appreciate your patronage. We look forward to your next transaction."
}