{
    "BTC": "BTC",
    "CAD": "CAD",
    "Mobile Verification": "Verificación móvil",
    "Wallet Info": "Monedero Info",
    "Enter your Mobile Number": "Ingrese su número de móvil",
    "Please enter your mobile number to verify your identity": "Por favor, introduzca su número de móvil para verificar su identidad",
    "Proceed": "Proceda",
    "For any assistance please call ": "Para cualquier ayuda, por favor llame",
    "Cancel": "Cancelar",
    "Select Language": "Selecciona Idioma",
    "English": "Inglés",
    "Buy": "Comprar",
    "Sell": "Vender",
    "Enter the Verification Code": "Ingrese el código de verificación",
    "Please enter the verification code sent to your mobile": "Por favor introduce el código de verificación enviado a tu móvil",
    "I'm Done": "He terminado",
    "Close": "Cerrar",
    "Sell Bitcoins": "Vender Bitcoins",
    "Deposit coins": "Monedas de Depósito",
    "Receive Cash": "Recibir Efectivo",
    "Receive cash": "Recibir dinero",
    "Receive Bitcoins": "Recibe Bitcoins",
    "Deposit Cash": "Depósito en efectivo",
    "Identity Verification": "Verificación de Identidad",
    "Insert Cash": "Inserte Cash",
    "Notes only.": "Sólo notas.",
    "Wallet Address": "Monedero Dirección",
    "I'm Done": "He terminado",
    "Total": "Total",
    "Enter Verification Code": "Ingrese el código de verificación",
    "Please enter the 6-Digit verification code sent to your mobile": "Por favor introduce el código de verificación de 6 dígitos a su móvil",
    "Wallet creation successful": "Creación Monedero éxito",
    "Please collect your paper wallet from the tray below": "Por favor, recoger su cartera papel de la bandeja de abajo",
    "Wallet Scan": "Monedero Scan",
    "Make sure that your entire QR Code is visible on the screen left": "Asegúrese de que todo el código QR es visible a la izquierda de pantalla",
    "It may take upto an hour for your coins to show up on your wallet.": "Se puede tomar hasta una hora para que sus monedas se muestren en su billetera.",
    "It may an hour for the coins to show up on your wallet.": "Puede una hora para las monedas para aparecer en su billetera.",
    "Please Wait": "Por favor espera",
    "Coins are Being Sent": "Las monedas se están enviando",
    "Redeem Code": "Canjear Código",
    "Please enter the amount of": "Por favor ingrese la cantidad de",
    "you would like to withdrawal.": "que le gustaría a la retirada.",
    "Approx": "Aprox",
    "Approx.": "Aprox.",
    "Select the amount you would like to withdraw": "Seleccione la cantidad que desea retirar",
    "The exact amount you requested is unavailable. Please select an amount below.": "La cantidad exacta que usted solicitó no está disponible. Por favor, seleccione una cantidad por debajo.",
    "Deposit Coins": "Depósito Monedas",
    "Send Bitcoins": "Enviar Bitcoins",
    "Please send": "Por favor envíe",
    "to the address on the left": "a la dirección de la izquierda",
    "We are currently Searching for your transaction": "Actualmente estamos en busca de su transacción",
    "We're very sorry, the machine is temporarily out of service.": "Lo sentimos mucho, la máquina se encuentra temporalmente fuera de servicio.",
    "Transaction Limit": "Límite de transacción",
    "Bitcoin Teller Machine": "Bitcoin cajero",
    "You have 180 seconds": "Usted tiene 180 segundos",
    "You have ": "Tienes",
    "Would you like to purchase more than ": "¿Te gustaría comprar más de",
    "worth of Bitcoins?": "pena de Bitcoins?",
    "Yes": "Sí",
    "No": "No",
    "Please Select Your Country": "Seleccione su país",
    "The country selected should match your government-issued photo ID.": "El país seleccionado debe coincidir con su identificación oficial con foto.",
    "France": "Francia",
    "Belgium": "Bélgica",
    "Germany": "Alemania",
    "Netherlands": "Países Bajos",
    "Please Select your Type of ID": "Por favor seleccione su tipo de ID",
    "Only accepted forms of ID are listed.": "Se enumeran las formas aceptadas de identificación única.",
    "ID Card": "Tarjeta de identificación",
    "Passport": "Pasaporte",
    "ID Card Scan": "ID Card Scan",
    "Press Continue once your ID Card is in focus and fully visible.": "Pulse Continuar una vez que su tarjeta de identificación está en foco y totalmente visible.",
    "Confirm ID Card Scan": "Confirmar ID Scan Card",
    "Click confirm if this photo is clear and focused": "Haga clic en confirmar si esta foto es clara y enfocada",
    "Scan Again": "Scan de nuevo",
    "Confrim": "Confrim",
    "Take Photo": "Tomar foto",
    "Please click proceed when your face is fully visible in the photo frame": "Por favor, haga clic en continuar cuando su rostro esté completamente visible en el marco de fotos",
    "Confirm Photo": "Confirmar fotos",
    "Please confirm that your face is fully visible in this photo": "Por favor, confirme que su cara es totalmente visible en esta foto",
    "Take Again": "Tome nuevo",
    "Do you have a Bitcoin Wallet?": "¿Tienes un Bitcoin Wallet?",
    "Kindly please have the QR Code of your Bitcoin Wallet": "Por favor tenga a mano el código QR de tu Monedero Bitcoin",
    "Dollars only": "Sólo Dólares",
    "Top up successful": "Rellenar con éxito",
    "has been sent to": "ha sido enviado a",
    "It may take an hour for the coins to show up on your wallet.": "Se puede tomar una hora para las monedas que aparecen en su billetera.",
    "START": "INICIO",
    "Wallet": "Monedero",
    "Bitcoins": "Bitcoins",
    "Please select one of the following options": "Por favor, seleccione una de las siguientes opciones",
    "Verify Identity": "Verificar identidad",
    " Buy Bitcoins ": "Comprar Bitcoins",
    " Sell Bitcoins ": "Vender Bitcoins",
    "ID Document": "ID de documento",
    "Face Scan": "Scan Face",
    "If you would like to transact more than ": "Si usted desea realizar transacciones más",
    "worth of Bitcoins, additional ID is required.": "pena de Bitcoins, se requiere identificación adicional.",
    "Verify my ID": "Verificación de identificación",
    "Go Back": "Volver",
    "The exact amount you requested is not currently available.": "La cantidad exacta que ha solicitado no está disponible actualmente.",
    "Please note that withdrawals above ": "Tenga en cuenta que los retiros anteriores",
    "will require additional time to process. This can take up to one hour. You will receive an SMS when your transaction has been verified.": "se necesitará más tiempo para procesar. Esto puede tomar hasta una hora. Usted recibirá un SMS cuando su transacción ha sido verificada.",
    "Withdrawals above ": "Los retiros anteriores",
    "will require additional confirmation. You will receive an SMS when your transaction has been verified.": "requerirá una confirmación adicional. Usted recibirá un SMS cuando su transacción ha sido verificada.",
    "will require additional confirmation.": "requerirá una confirmación adicional.",
    "You will receive an SMS when your transaction has been verified.": "Usted recibirá un SMS cuando su transacción ha sido verificada.",
    "Withdrawal Pending": "Retiro Pendiente",
    " sold and ": "vendido y",
    " will be dispensed.": "será dispensado.",
    "Transactions above ": "Las transacciones anteriores",
    " require additional time to verify. You will receive an SMS within one hour to complete your transaction.": "requerir tiempo adicional para verificar. Usted recibirá un SMS en una hora para completar su transacción.",
    "Identity": "Identidad",
    "Disclaimer": "Descargo de responsabilidad",
    "I agree": "Acepto estos términos y condiciones.",
    "Refund Code": "Código de reembolso",
    "Enter Refund Code": "Ingrese Reembolso Código",
    "Please enter the 8-Digit refund code sent to your mobile.": "Por favor introduce el código de reembolso de 8 dígitos a su móvil.",
    "Continue": "Continuar",
    "Refund Complete": "Reembolso completo",
    "Refill Complete": "Vuelva a llenar completa",
    " inserted into cash recycler": "insertada en reciclador de efectivo",
    "Please confirm your country of residence": "Confirme por favor su país de residencia",
    "United States": "Estados Unidos",
    "Canada": "Canadá",
    "Mexico": "México",
    "Select another country": "Seleccione otro país",
    "Confirm & Proceed": "Confirmar y Continuar",
    " will require identity verification.": "requerirá la verificación de identidad.",
    "Make sure that your entire QR Code is visible on the screen below": "Asegúrese de que todo el código QR es visible en la pantalla de abajo",
    "Verify": "Compruebe",
    "received and": "recibido y",
    "Print Receipt": "Imprimir recibo",
    "Capture Photo": "Photo Capture",
    "Capture": "Captura",
    "Scan Wallet": "Monedero Scan",
    "Scan the QR Code wallet": "Busque en la billetera Código QR",
    "Send": "Enviar",
    "Once done click on proceed": "Una vez hecho esto, haga clic en continuar",
    "Withdrawal successful": "La retirada exitosa",
    " dispensed.": "dispensado.",
    "Please select edit one of the following options": "Por favor, seleccione editar una de las siguientes opciones",
    "Redeem": "Canjear",
    "Code": "Código",
    "Refund": "Reembolso",
    "Refill Note Recycler": "Recambio Note Recycler",
    "Please wait until we identify your transaction": "Por favor, espere hasta que identifiquemos su transacción",
    "Please wait": "Por favor espera",
    "Please include a Transaction fee if prompted": "Por favor, incluya un cargo por transacción si se le pide",
    "Back": "Volver",
    "banknotes only": "sólo los billetes",
    "Current Transaction Limit ": "Límite de Transacción actual",
    "Transaction limit after ID Verification ": "Límite de transacciones después de la verificación de identidad",
    "Thank you": "Gracias",
    "We appreciate your patronage. We look forward to your next transaction.": "Apreciamos su patrocinio. Esperamos con interés su próxima transacción.",
    "Pending": "A la espera de",
    " require additional time to verify. You will receive an SMS shortly, once the we have received ": "requerir tiempo adicional para verificar. Usted recibirá un SMS en breve, una vez que la hemos recibido",
    " confrirmations.": "confirmaciones.",
    "Collect Cash": "Recoger Cash",
    "Please collect your cash from the tray below": "Por favor, recoger el dinero en efectivo de la bandeja de abajo",
    "Requested": "Solicitado",
    "Dispensed": "Distribuida",
    "Remaining": "Restante",
    "Please include a Transaction fee if prompted. If you do not include a fee, your transaction WILL BE DELAYED.": "Por favor, incluya un cargo por transacción si se le solicita. Si usted no incluye un cargo, su transacción será retrasado.",
    "Ensure you include Transaction fee if prompted.": "Asegúrese de incluir tarifa de transacción si se le solicita.",
    "ALWAYS include transaction fee if prompted.": "SIEMPRE incluir tarifa de transacción si se le solicita.",
    "ALWAYS include a transaction fee if prompted.": "Siempre incluya un cargo por transacción si se le solicita.",
    "Send exactly": "Enviar exactamente",
    "Scan the QR Code with your wallet": "Escanear el código QR con su billetera",
    "Open your Wallet APP and scan": "Abra el APP Monedero y escanear",
    "Scan QR Code Now": "Escanear código QR Ahora",
    "Scan with your wallet app.": "Analiza con tu aplicación billetera.",
    "ALWAYS include a transaction fee.": "Siempre incluya un cargo por transacción.",
    "Always include a transaction fee.": "Siempre incluya un cargo por transacción.",
    "You will receive an SMS shortly, please return to the machine at that time.": "Usted recibirá un SMS en breve, por favor volver a la máquina en ese momento.",
    " require additional time to verify. This usually takes": "requerir tiempo adicional para verificar. Esto usualmente toma",
    " minutes.": "minutos.",
    "I accept these terms and conditions.": "Acepto estos términos y condiciones.",
    "Insufficient Cash": "Insuficiente Cash",
    "We do not have sufficient cash at this moment. We will refund you respective Bitcoins for the remaining 5 CAD": "No tenemos suficiente dinero en efectivo en este momento. Le devolveremos respectivos Bitcoins para el 5 CAD restante",
    "We are sorry, we do not have sufficient cash for your request. We will refund you": "Lo sentimos, no tenemos suficiente dinero en efectivo para su solicitud. Le devolveremos",
    "BTC for the remaining": "BTC para los restantes",
    "Proceed to Scan you wallet": "Proceda a digitalizar tu cartera",
    "Buy Bitcoins": "Comprar Bitcoins"
}