{
	"BTC": "BTC",
	"CAD": "CAD",
	"Mobile Verification": "Vérification GSM",
	"Wallet Info": "Info Portefeuille",
	"Buy Bitcoins": "Achat Bitcoins",
	"Enter your Mobile Number": "Entrez votre numéro de GSM",
	"Please enter your mobile number to verify your identity": "Veuillez entrer votre numéro de GSM pour vérifier votre identité",
	"Proceed": "Continuer",
	"For any assistance please call ": "Pour toute aide, veuillez appeler ",
	"Cancel": "Annuler",
	"Select Language": "Choisir la langue",
	"English": "Français",
	"Buy": "Acheter",
	"Sell": "Vendre",
	"Enter the Verification Code": "Entrez le numéro de vérification",
	"Please enter the verification code sent to your mobile": "Veuillez entrer le numéro de vérification envoyé à votre GSM (6 chiffres)",
	"I'm Done": "J'ai terminé; continuer",
	"Close": "Fermer",
	"Sell Bitcoins": "Vendre des Bitcoins",
	"Deposit coins": "Versement des Bitcoins",
	"Receive Cash": "Retirer l'argent",
	"Receive cash": "Retirer l'argent",
	"Receive Bitcoins": "Versement des Bitcoins",
	"Deposit Cash": "Versement en liquide",
	"Identity Verification": "Vérification d'identité ",
	"Insert Cash": "Insérer billet(s)",
	"Notes only.": "Billets seulement",
	"Wallet Address": "Adresse portefeuille",
    "I'm Done": "J'ai terminé; continuer",
	"Total": "Total",
	"Enter Verification Code": "Entrez le numéro de vérification",
	"Please enter the 6-Digit verification code sent to your mobile": "Veuillez entrer le numéro de vérification envoyé à votre GSM (6 chiffres)",
	"Wallet creation successful": "Création de portefeuille réussie",
	"Please collect your paper wallet from the tray below": "Veuillez récupérer votre portefeuille de l'imprimante ci-dessous",
	"Wallet Scan": "Scan du portefeuille",
	"Make sure that your entire QR Code is visible on the screen left": "Assurez-vous que votre code QR apparait entièrement sur l'écran à gauche",
	"It may take up to an hour for your coins to show up on your wallet.": "Vos Bitcoins peuvent mettre jusqu'à une heure pour apparaître sur votre portefeuille.",
	"It may take an hour for the coins to show up on your wallet.": "Vos Bitcoins peuvent mettre jusqu'à une heure pour apparaître sur votre portefeuille.",
	"Please Wait": "Veuillez patienter",
	"Coins are Being Sent": "Les Bitcoins sont en cours d'envoi",
	"Redeem Code": "Utiliser Code",
	"Please enter the amount of": "S'il vous plaî,t indiquez la somme de",
	"you would like to withdrawal.": "que vous souhaitez retirer",
	"Approx": "Approx",
	"Approx.": "Approx.",
	"Select the amount you would like to withdraw": "Choisissez le montant que vous souhaitez retirer",
	"The exact amount you requested is unavailable. Please select an amount below.": "Le montant exact requis n'est pas disponible. Veuillez sélectionner un montant inférieur.",
	"Deposit Coins": "Versement des Bitcoins",
	"Send Bitcoins": "Envoyer des Bitcoins",
	"Please send": "Veuillez envoyer",
	"to the address on the left": "à l'adresse indiquée à gauche",
	"We are currently Searching for your transaction": "Nous recherchons actuellement votre transaction",
	"We're very sorry, the machine is temporarily out of service.": "Nous sommes désolés, la machine est temporairement hors-service.",
	"Transaction Limit": "Limite de transaction",
	"Bitcoin Teller Machine": "Bitcoin Guichet Automatique",
	"You have 180 seconds": "Vous avez 180 secondes",
	"You have ": "Vous avez ",
	"Would you like to purchase more than ": "Voulez-vous acheter plus de",
	"worth of Bitcoins?": "en Bitcoins?",
	"Yes": "Oui",
	"No": "Non",
	"Please Select Your Country": "Veuillez choisir votre pays",
	"The country selected should match your government-issued photo ID.": "Le pays choisi devrait correspondre à votre pièce d'identité émise par les autorités.",
	"France": "France",
	"Belgium": "Belgique",
	"Germany": "Allemagne",
	"Netherlands": "Pays-Bas",
	"Please Select your Type of ID": "Veuillez choisir votre type de pièce d'identité",
	"Only accepted forms of ID are listed.": "Voici la liste des pièces d'identité admises",
	"ID Card": "Carte d'identité",
	"Passport": "Passeport",
	"ID Card Scan": "Scan carte d'identité",
	"Press Continue once your ID Card is in focus and fully visible.": "Veuillez appuyer sur Continuer une fois que votre carte d'identité est nette et clairement visible.",
	"Confirm ID Card Scan": "Confirmez le scan de la carte d'identité",
	"Click confirm if this photo is clear and focused": "Cliquez sur confirmer si cette photo est claire et nette",
	"Scan Again": "Nouveau scan",
	"Confirm": "Confirmez",
	"Take Photo": "Prendre la photo",
	"Please click proceed when your face is fully visible in the photo frame": "Veuillez cliquer sur continuer lorsque votre visage est pleinement visible dans le cadre photo",
	"Confirm Photo": "Confirmez la photo",
	"Please confirm that your face is fully visible in this photo": "Veuillez confirmer que votre visage est pleinement visible sur cette photo",
	"Take Again": "Reprendre la photo",
	"Do you have a Bitcoin Wallet?": "Avez-vous un portefeuille Bitcoin?",
	"Kindly please have the QR Code of your Bitcoin Wallet": "Veuillez vous munir du code QR de votre portefeuille Bitcoin",
	"Dollars only": "Dollars uniquement",
	"Top up successful": "Succès",
	"has been sent to": "ont été envoyé à",
	"It may take an hour for the coins to show up on your wallet.": "Vos Bitcoins peuvent mettre jusqu'à une heure pour apparaître sur votre portefeuille.",
	"START": "START",
	"Wallet": "Portefeuille",
	"Bitcoins": "Bitcoins",
	"Please select one of the following options": "Veuillez choisir l'une des options suivantes",
	"Verify Identity": "Vérifier l'identité",
	" Buy Bitcoins ": " Acheter des Bitcoins ",
	" Sell Bitcoins ": " Vendre des Bitcoins ",
	"ID Document": "Document d'identité",
	"Face Scan": "Scan du visage",
	"If you would like to transact more than ": "Si vous voulez effectuer une transaction de plus de ",
	"worth of Bitcoins, additional ID is required.": "en Bitcoins, une pièce d'identité supplémentaire est nécessaire",
	"Verify my ID": "Vérifier ma pièce d'identité",
	"Go Back": "Retour",
	"The exact amount you requested is not currently available.": "Le montant exact requis n'est pas disponible.",
	"Please note that withdrawals above ": "Veuillez noter que les retraits supérieurs à ",
	"will require additional time to process. This can take up to one hour. You will receive an SMS when your transaction has been verified.": "nécessiteront un délai supplémentaire pour se faire. Ceci peut prendre jusqu'à une heure. Vous recevrez un SMS lorsque votre transaction aura été vérifiée.",
	"Withdrawals above ": "Les retraits supérieurs à ",
	"will require additional confirmation. You will receive an SMS when your transaction has been verified.": "nécessiteront une confirmation supplémentaire. Vous recevrez un SMS lorsque votre transaction aura été vérifiée.",
	"will require additional confirmation.": "nécessiteront une confirmation supplémentaire.",
	"You will receive an SMS when your transaction has been verified.": "Vous recevrez un SMS lorsque votre transaction aura été vérifiée.",
	"Withdrawal Pending": "Retrait en attente",
	" sold and ": " vendu et ",
	" will be dispensed.": " seront distribués.",
	"Transactions above ": "Les transactions supérieurs à ",
	" require additional time to verify. You will receive an SMS within one hour to complete your transaction.": " nécessitent un délai de vérification supplémentaire. Vous recevrez un SMS d'ici une heure pour compléter votre transaction.",
	"Identity": "Identité",
	"Disclaimer": "Clauses limitatives",
	"I agree": "J'accepte",
	"Refund Code": "Code de remboursement",
	"Enter Refund Code": "Entrez le code de remboursement",
	"Please enter the 8-Digit refund code sent to your mobile.": "Veuillez entrer le code de remboursement à 8 chiffres envoyé sur votre GSM",
	"Continue": "Continuer",
	"Refund Complete": "Remboursement complété",
	"Refill Complete": "Remise à niveau complété",
	" inserted into cash recycler": " inséré dans le cash recycler",
	"Please confirm your country of residence": "Veuillez confirmer votre pays de résidence",
	"United States": "Etats-Unis",
	"Canada": "Canada",
	"Mexico": "Mexique",
	"Select another country": "Choisissez un autre pays",
	"Confirm & Proceed": "Confirmer et Continuer",
	" will require identity verification.": " une vérification d'identité sera nécessaire",
	"Make sure that your entire QR Code is visible on the screen below": "Vérifiez que tout votre code QR est visible sur l'écran en bas",
	"Verify": "Vérifier",
	"received and": "reçu et",
	"Print Receipt": "Imprimez le reçu",
	"Capture Photo": "Prise de photo",
	"Capture": "Prise",
	"Scan Wallet": "Scan portefeuille",
	"Scan the QR Code wallet": "Veuillez scanner le code QR",
	"Send": "Envoyer",
	"Once done click on proceed": "Une fois terminé, cliquez sur continuer",
	"Withdrawal successful": "Retrait réussi",
	" dispensed.": " distribué.",
	"Please select edit one of the following options": "Veuillez choisir l'une des options suivantes",
	"Redeem": "Utiliser",
	"Code": "Code",
	"Refund": "Remboursement",
	"Refill Note Recycler": "Remplir le Note Recycler",
	"Please wait until we identify your transaction": "Veuillez attendre que nous identifions votre transaction",
	"Please wait": "Veuillez attendre",
	"Please include a Transaction fee if prompted": "Veuillez inclure des frais de transaction si demandé",
	"Back": "Retour",
	"banknotes only": "Billets de banque uniquement",
	"Current Transaction Limit ": "Limite de transaction actuelle ",
	"Transaction limit after ID Verification ": "Limite de transaction après vérification d'identité",
	"I, agree": "Je, suis d'accord",
	"Thank you": "Merci",
	"We appreciate your patronage. We look forward to your next transaction.": "Nous sommes heureux de vous avoir eu comme client. A bientôt pour une nouvelle transaction.",
	"Pending": "En attente",
	" require additional time to verify. You will receive an SMS shortly, once the we have received ": " nécessitent un délai supplémentaire pour la vérification. Vous recevrez un SMS d'ici peu, une fois que nous aurons reçu ",
	" confirmations.": " confirmations.",
	"I accept these terms and conditions.": "J’accepte ces termes et ces conditions."
}