{
	"Select Language": "Izaberite jezik",
	"English": "Hrvatski",
	"Bitcoin Teller Machine": "Bitcoin bankomat",
	"START": "ZAPOČNI",
	"Identity": "Identitet",
	"Wallet": "Novčanik",
	"Bitcoins": "Bitcoini",
	"Disclaimer": "Izjava o odgovornosti",
	"I accept these terms and conditions.": "Prihvaćam uvjete.",
	"Cancel": "Odustani",
	"Identity Verification": "Provjera indentiteta",
	"Wallet Info": "Podaci o novčaniku",
	"Enter your Mobile Number": "Unesite broj mobitela",
	"Please enter your mobile number to verify your identity": "Unesite broj mobitela radi provjere identiteta",
	"Proceed": "Nastavi",
	"We're very sorry, the machine is temporarily out of service.": "Ispričavamo se, uređaj privremeno nije u funkciji.",
	"Close": "Zatvori",
	"Buy Bitcoins": "Kupi bitcoine",
	"Enter Verification Code": "Unesite verifikacijski kod",
	"Please enter the 6-Digit verification code sent to your mobile": "Unesite šesteroznamenkasti verifikacijski kod poslan na Vaš mobitel",
	"Please select one of the following options": "Izaberite jednu od ponuđenih opcija",
	"Current Transaction Limit ": "Trenutno ograničenje prijenosa ",
	"Buy": "Kupi",
	"Sell": "Prodaj",
	"Redeem": "Otkupi",
	"Code": "Kod",
	"Verify": "Provjeri",
	"Refund": "Povrat sredstava",
	"Refill Note Recycler": "Nadopunite reciklator novčanica",
	"Do you have a Bitcoin Wallet?": "Imate li Bitcoin novčanik?",
	"Kindly please have the QR Code of your Bitcoin Wallet": "Pokažite QR-kod Vašeg Bitcoin novčanika",
	"Yes": "Da",
	"No": "Ne",
	"Wallet Scan": "Sken novčanika",
	"Make sure that your entire QR Code is visible on the screen below": "Provjerite je li QR-kod potpuno vidljiv na ekranu ispod",
	"Back": "Nazad",
	"Your Wallet is Printing": "Novčanik se ispisuje",
	"Please collect your paper wallet from the tray below": "Uzmite otisnuti novčanik",
	"ID Document": "Identifikacijski dokument",
	"Face Scan": "Sken lica",
	"Please Select your Type of ID": "Izaberite tip identifikacijskog dokumenta",
	"Only accepted forms of ID are listed.": "Prihvaćaju se samo navedeni dokumenti.",
	"ID Card": "Osobna iskaznica",
	"Passport": "Putovnica",
	"Capture": "Slikaj",
	"Confirm ID Card Scan": "Potvrdite sken osobne iskaznice",
	"Click confirm if this photo is clear and focused": "Potvrdite je li slika jasna",
	"Scan Again": "Skeniraj ponovno",
	"Confrim": "Potvrdi",
	"Confirm Photo": "Prihvati sliku",
	"Please confirm that your face is fully visible in this photo": "Molimo, potvrdite je li Vaše lice u potpunosti vidljivo na slici",
	"Take Again": "Slikaj ponovno",
	"Transaction Limit": "Ograničenje prijenosa",
	"Insert Cash": "Umetnite gotovinu",
	"banknotes only": "Samo novčanice",
	"Total": "Ukupno",
	"Wallet Address": "Adresa novčanika",
	"I'm Done": "Završi",
	"Please Wait": "Molimo, pričekajte",
	"Coins are Being Sent": "Bitcoini se šalju",
	"Top up successful": "Nadopuna uspješna",
	"received and": "primljeno i",
	"has been sent to": "poslano na",
	"It may take an hour for the coins to show up on your wallet.": "Transakcija može potrajati i do jedan sat.",
	"Print Receipt": "Otisnite račun",
	"Deposit Coins": "Uplatite bitcoine",
	"Redeem Code": "Otkupite kod",
	"Withdrawals above ": "Povlačenja iznad ",
	"will require additional confirmation.": "potrebna je dodatna potvrda.",
	"You will receive an SMS when your transaction has been verified.": "Primit ćete SMS nakon što transakcija bude potvrđena.",
	"Approx.": "Približno",
	"Select the amount you would like to withdraw": "Izaberite iznos koji želite podići",
	"The exact amount you requested is not currently available.": "Zatraženi iznos trenutno nije raspoloživ.",
	"You have ": "Imate ",
	"Receive Cash": "Primi gotovinu",
	"Scan QR Code Now": "Skeniraj QR-kod",
	"Send Bitcoins": "Pošalji bitcoine",
	"Scan with your wallet app.": "Skeniraj s wallet aplikacijom",
	"Send exactly": "Pošalji točno",
	"Always include a transaction fee.": "Uvijek uključi naknadu za transakciju.",
	"Mobile Verification": "Mobilna verifikacija",
	"Deposit coins": "Položi bitcoine",
	"Collect Cash": "Uzmite gotovinu",
	"Please collect your cash from the tray below": "Uzmite gotovinu",
	"Requested": "Zatraženo",
	"Dispensed": "Isplaćeno",
	"Remaining": "Preostalo",
	"Withdrawal successful": "Transakcija uspješna",
	" sold and ": " prodan i ",
	" dispensed.": " isplaćen.",
	"Pending": "Čekanje",
	" will be dispensed.": " biti će isplaćen.",
	"Transactions above ": "Transakcije iznad ",
	" require additional time to verify. This usually takes": " treba dodatno vrijeme za potvrdu. To približno traje",
	" minutes.": " minuta.",
	"You will receive an SMS shortly, please return to the machine at that time.": "Uskoro ćete primiti SMS, vratite se tada do uređaja.",
	"Refill Complete": "Punjenje završeno",
	" inserted into cash recycler": " ubačeno u reciklator gotovine",
	"Refund Code": "Kod za povrat",
	"Receive Bitcoins": "Primi bitcoine",
	"Enter Refund Code": "Unesite kod za povrat",
	"Please enter the 8-Digit refund code sent to your mobile.": "Unesite osmeroznamenkasti kod za povrat poslan na Vaš mobitel.",
	"Continue": "Nastavak",
	"Refund Complete": "Povrat završen",
	"Thank you": "Hvala",
	"We appreciate your patronage. We look forward to your next transaction.": "Zahvaljujemo. Veselimo se vašoj sljedećoj transakciji."
}