{
	"BTC": "BTC",
	"CAD": "CAD",
	"Mobile Verification": "Mobiele verificatie",
	"Wallet Info": "Wallet-informatie",
	"Buy Bitcoins": "Bitcoins kopen",
	"Enter your Mobile Number": "Voer uw mobiel nummer in",
	"Please enter your mobile number to verify your identity": "Voer uw mobiel nummer in om uw identiteit te verifiëren",
	"Proceed": "Doorgaan",
	"For any assistance please call ": "Neem voor ondersteuning contact op met",
	"Cancel": "Annuleren",
	"Select Language": "Kies uw taal",
	"English": "Nederlands",
	"Buy": "Kopen",
	"Sell": "Verkopen",
	"Enter the Verification Code": "Voer de verificatiecode in",
	"Please enter the verification code sent to your mobile": "Voer de verificatiecode in die naar uw mobiel werd verstuurd ",
	"I'm Done": "Klaar",
	"Close": "Sluiten",
	"Sell Bitcoins": "Bitcoins verkopen",
	"Deposit coins": "Coins storten",
	"Receive Cash": "Cash ontvangen",
	"Receive cash": "Cash ontvangen",
	"Receive Bitcoins": "Bitcoins ontvangen",
	"Deposit Cash": "Cash storten",
	"Identity Verification": "Verificatie van uw identiteit",
	"Insert Cash": "Cash invoeren",
	"Notes only.": "Enkel biljetten",
	"Wallet Address": "Wallet-adres",
	"Im Done": "Klaar",
	"Total": "Totaal",
	"Enter Verification Code": "Voer de verificatiecode in",
	"Please enter the 6-Digit verification code sent to your mobile": "Voer de 6-cijferige verificatiecode in die naar uw mobiel werd gestuurd",
	"Wallet creation successful": "Wallet aangemaakt",
	"Please collect your paper wallet from the tray below": "Haal uw paper wallet uit het bakje onderaan",
	"Wallet Scan": "Scan uw wallet",
	"Make sure that your entire QR Code is visible on the screen left": "Zorg ervoor dat de volledige QR-code zichtbaar is op het scherm links",
	"It may take upto an hour for your coins to show up on your wallet.": "Het kan tot een uur duren voordat de coins op uw wallet verschijnen",
	"It may an hour for the coins to show up on your wallet.": "Het kan een uur duren voordat de coins op uw wallet verschijnen",
	"Please Wait": "Wacht even",
	"Coins are Being Sent": "Coins worden verstuurd",
	"Redeem Code": "Code verzilveren",
	"Please enter the amount of": "Voer het bedrag in",
	"you would like to withdrawal.": "dat u wilt afhalen",
	"Approx": "Ongeveer",
	"Approx.": "Ongeveer",
	"Select the amount you would like to withdraw": "Kies het bedrag dat u wilt afhalen",
	"The exact amount you requested is unavailable. Please select an amount below.": "Het gevraagde bedrag is niet beschikbaar, maak uw keuze uit onderstaande bedragen.",
	"Deposit Coins": "Coins storten",
	"Send Bitcoins": "Bitcoins versturen",
	"Please send": "Versturen",
	"to the address on the left": "naar het adres links getoond",
	"We are currently Searching for your transaction": "We zoeken momenteel naar uw transactie",
	"Were very sorry, the machine is temporarily out of service.": "Onze excuses, deze machine is tijdelijk buiten werking.",
	"Transaction Limit": "Transactielimiet",
	"Bitcoin Teller Machine": "Bitcoin geldautomaat",
	"You have 180 seconds": "U heeft 180 seconden",
	"You have ": "U heeft",
	"Would you like to purchase more than ": "Wilt u meer kopen dan",
	"worth of Bitcoins?": "de waarde van de Bitcoins?",
	"Yes": "Ja",
	"No": "Neen",
	"Please Select Your Country": "Kies uw land",
	"The country selected should match your government-issued photo ID.": "Het gekozen land moet overeenkomen met het land vermeld op uw identiteitsbewijs",
	"France": "Frankrijk",
	"Germany": "Duitsland",
	"Netherlands": "Nederland",
	"Please Select your Type of ID": "Kies het type identiteitsbewijs",
	"Only accepted forms of ID are listed.": "Alle identiteitsbewijzen die worden aanvaard, staan hier opgesomd.",
	"ID Card": "Identiteitskaart",
	"Passport": "Paspoort",
	"ID Card Scan": "Scan uw identiteitskaart",
	"Press Continue once your ID Card is in focus and fully visible.": "Druk op Doorgaan als uw identiteitskaart volledig en duidelijk zichtbaar is.",
	"Confirm ID Card Scan": "Bevestig de scan van uw identiteitskaart",
	"Click confirm if this photo is clear and focused": "Klik op bevestigen als de foto scherp en helder is.",
	"Scan Again": "Opnieuw scannen",
	"Confrim": "Bevestigen",
	"Take Photo": "Foto nemen",
	"Please click proceed when your face is fully visible in the photo frame": "Klik op doorgaan als uw gezicht volledig zichtbaar is in het fotokader.",
	"Confirm Photo": "Bevestig foto",
	"Please confirm that your face is fully visible in this photo": "Bevestig dat uw gezicht volledig zichtbaar is op deze foto",
	"Take Again": "Opnieuw nemen",
	"Do you have a Bitcoin Wallet?": "Heeft u een Bitcoin Wallet?",
	"Kindly please have the QR Code of your Bitcoin Wallet": "Hier is de QR-code van uw Bitcoin Wallet ",
	"START": "START",
	"Identity": "Identiteit",
	"Wallet": "Wallet",
	"Bitcoins": "Bitcoins",
	"Disclaimer": "Disclaimer",
	"I agree": "Ik ga akkoord",
	"Refund Code": "Code voor terugbetaling",
	"Enter Refund Code": "Voer de code voor terugbetaling in",
	"Please enter the 8-Digit refund code sent to your mobile.": "Voer de 8-cijferige code voor terugbetaling in die naar uw mobiel werd verstuurd.",
	"Continue": "Doorgaan",
	"Refund Complete": "Terugbetaling voltooid",
	"Refill Complete": "Aangevuld",
	" inserted into cash recycler": "in cash-recyclingautomaat geplaatst",
	"Please confirm your country of residence": "Bevestig uw land van woonst",
	"United States": "Verenigde Staten",
	"Canada": "Canada",
	"Mexico": "Mexico",
	"Select another country": "Kies een ander land",
	"Confirm & Proceed": "Bevestig en ga verder",
	" will require identity verification.": "hiervoor moet uw identiteit worden geverifieerd.",
	"Make sure that your entire QR Code is visible on the screen below": "Zorg ervoor dat uw volledige QR-code zichtbaar is op het onderstaande scherm",
	"Verify": "Verifiëren",
	"received and": "ontvangen en",
	"Print Receipt": "Druk betaalbewijs af",
	"Capture Photo": "Foto nemen",
	"Capture": "Nemen",
	"Scan Wallet": "Scan Wallet",
	"Scan the QR Code wallet": "Scan de QR-Code wallet",
	"Send": "Versturen",
	"Once done click on proceed": "Als u klaar bent, klikt u op doorgaan ",
	"Withdrawal successful": "Opname gelukt",
	" dispensed.": "verstrekt.",
	"Please select edit one of the following options": "Kies één van de volgende opties",
	"Redeem": "Verzilveren",
	"Code": "Code",
	"Refund": "Terugbetaling",
	"Refill Note Recycler": "Biljetrecycler opnieuw vullen",
	"Please wait until we identify your transaction": "Wacht tot we uw transactie hebben geïdentificeerd",
	"Please wait": "Wacht even",
	"Please include a Transaction fee if prompted": "Reken een transactievergoeding bij, indien gevraagd",
	"Back": "Terug",
	"banknotes only": "enkel bankbiljetten",
	"Current Transaction Limit ": "Huidige transactielimiet ",
	"Transaction limit after ID Verification ": "Transactielimiet na ID-verificatie",
	"I, agree": "Ik ga akkoord",
	"Thank you": "Bedankt",
	"We appreciate your patronage. We look forward to your next transaction.": "Hartelijk dank. Wij kijken uit naar uw volgende transactie.",
	"Pending": "Nog af te ronden",
	" require additional time to verify. You will receive an SMS shortly, once the we have received ": "Extra tijd nodig voor verificatie. U ontvangt binnenkort een SMS wanneer wij een",
	" confirmations.": "bevestiging hebben ontvangen.",
	"I accept these terms and conditions.": "Ik aanvaard uw aankoopvoorwaarden.",
	"Please select one of the following options": "Selecteer een van de volgende opties",
	"Enter Redeem Code": "Voer Redeem Code",
	"Collect Cash": "Verzamelen bankbiljetten",
	"Please collect your cash from the tray below": "Vraag eerst uw geld uit de onderstaande lade",
	"Dispensed": "Gedoseerd",
	"Requested": "Gevraagd",
	"Remaining": "Resterende",
	"We're very sorry, the machine is temporarily out of service.": "We're very sorry, the machine is temporarily out of service."
}