{
	"Select Language": "Izberite jezik", 
	"English": "Slovenščina", 
	"Bitcoin Teller Machine": "Bitcoin bankomat", 
	"START": "Začetek", 
	"Identity": "Identiteta",
	"Wallet": "Denarnica", 
	"Bitcoins": "Bitcoini", 
	"Disclaimer": "pogoji uporabe",
	"I accept these terms and conditions.": "Sprejemam pogoje uporabe", 
	"Cancel": "Prekinitev", 
	"Identity Verification": "Preverjanje/Potrditev identifikacije", 
	"Wallet Info": "Informacije o denarnici", 
	"Enter your Mobile Number": "Vnesite svojo mobilno številko",
	"Please enter your mobile number to verify your identity": "Prosimo, vnesite svojo mobilno številko za potrditev identitete", 
	"Proceed": "Potrdi", 
	"We're very sorry, the machine is temporarily out of service.": "Opravičujemo se, bankomat trenutno ne deluje.", 
	"Close": "Zaprto", 
	"Buy Bitcoins": "Kupi Bitcoine", 
	"Enter Verification Code": "Vnesite potrditveno kodo", 
	"Please enter the 6-Digit verification code sent to your mobile": "Prosimo, vnesite 6-mestno potrditveno kodo, ki ste jo prejeli na mobilni telefon", 
	"Please select one of the following options": "Prosimo, izberite eno izmed sledečih možnosti", 
	"Current Transaction Limit ": "Trenutni limit transakcije", 
	"Buy": "Kupi", 
	"Sell": "Prodaj", 
	"Redeem": "Zamenjaj",
	"Code": "Koda", 
	"Verify": "Preveri", 
	"Refund": "Povrni", 
	"Refill Note Recycler": "Vstavi bankovec",
	"Do you have a Bitcoin Wallet?": "Ali imate Bitcoin denarnico?", 
	"Kindly please have the QR Code of your Bitcoin Wallet": "Prosim, skenirajte QR kodo vaše Bitcoin denarnice", 
	"Yes": "Da", 
	"No": "Ne",
	"Wallet Scan": "Skeniranje denarnice", 
	"Make sure that your entire QR Code is visible on the screen below": "Celotna QR koda naj bo vidna na spodnjem zaslonu", 
	"Back": "Nazaj", 
	"Your Wallet is Printing": "Vaša denarnica se tiska", 
	"Please collect your paper wallet from the tray below": "Prosim, vzemite papirno denarnico", 
	"ID Document": "Osebni dokument", 
	"Face Scan": "Skeniranje obraza", 
	"Please Select your Type of ID": "Prosimo, izberite vrsto osebnega dokumenta", 
	"Only accepted forms of ID are listed.": "Seznam veljavnih osebnih dokumentov.", 
	"ID Card": "Osebna izkaznica", 
	"Passport": "Potni list",
	"Capture": "Foto",
	"Confirm ID Card Scan": "Potrdite skeniranje osebnega dokumenta", 
	"Click confirm if this photo is clear and focused": "Pritisnite Potrdi, če je fotografija jasna in čista", 
	"Scan Again": "Skeniraj ponovno", 
	"Confrim": "Potrdi",
	"Confirm Photo": "Potrdi fotografijo",
	"Please confirm that your face is fully visible in this photo": "Prosimo potrdite, da je vaš obraz na fotografiji v celoti viden", 
	"Take Again": "Ponovi", 
	"Transaction Limit": "Transakcijski limit", 
	"Insert Cash": "Vnesite denar", 
	"banknotes only": "Samo bankovci",
	"Total": "Skupaj", 
	"Wallet Address": "Naslov denarnice", 
	"I'm Done": "Končano", 
	"Please Wait": "Prosimo, počakajte", 
	"Coins are Being Sent": "Bitcoini v pošiljanju", 
	"Top up successful": "Nakup je bil uspešno izveden",
	"received and": "prejeto in", 
	"has been sent to": "je bilo poslano", 
	"It may take an hour for the coins to show up on your wallet.": "Da se Bitcoini prikažejo v vaši denarnici lahko traja eno uro.", 
	"Print Receipt": "Natisni potrdilo", 
	"Deposit Coins": "Dvig Bitcoinov", 
	"Redeem Code": "Koda o potrditvi", 
	"Withdrawals above ": "Dvig nad ",
	"will require additional confirmation.": "zahteva dodatno potrditev.",
	"You will receive an SMS when your transaction has been verified.": "Ko bo vaša transakcija potrjena, boste prejeli SMS.", 
	"Approx.": "Približno", 
	"Select the amount you would like to withdraw": "Izberite vsoto, ki jo želite dvigniti",
	"The exact amount you requested is not currently available.": "Izbrane vrednosti trenutno ne moremo izplačati.", 
	"You have ": "Imate", 
	"Receive Cash": "Prejmi denar", 
	"Scan QR Code Now": "Skenirajte QR kodo", 
	"Send Bitcoins": "Pošlji Bitcoine", 
	"Scan with your wallet app.": "Sken z vašo denarnica aplikacijo.", 
	"Send exactly": "Pošlji natančno", 
	"Always include a transaction fee.": "Vedno vključi plačilo transakcije.", 
	"Mobile Verification": "Mobilna potrditev", 
	"Deposit coins": "Polog Bitcoinov", 
	"Collect Cash": "Vzemite denar", 
	"Please collect your cash from the tray below": "Prosimo, vzemite denar",
	"Requested": "Zahteva", 
	"Dispensed": "Izdano", 
	"Remaining": "Preostalo", 
	"Withdrawal successful": "Dvig je bil uspešno izveden", 
	" sold and ": " prodaj in ", 
	" dispensed.": " izdano.",  
	"Pending": "Postopek poteka, prosimo počakajte", 
	" will be dispensed.": " bo izdano.", 
	"Transactions above ": "Transakcija nad ", 
	" require additional time to verify. This usually takes": " zahteva dodaten čas za potrditev. Postopek običajno traja", 
	" minutes.": " minut.", 
	"You will receive an SMS shortly, please return to the machine at that time.": " SMS boste prejeli v kratkem, prosim vrnite se k avtoma.",
	"Refill Complete": "Polnitev končana", 
	" inserted into cash recycler": " vstavite v odprtino za denar", 
	"Refund Code": "Koda za vračilo", 
	"Receive Bitcoins": "Sprejmite Bitcoine", 
	"Enter Refund Code": "Vnesite kodo za vračilo", 
	"Please enter the 8-Digit refund code sent to your mobile.": "Prosimo, vnesite 8-mestno kodo za vračilo, ki ste jo prejeli na mobilni telefon.",
	"Continue": "Nadaljuj", 
	"Refund Complete": "Vračilo končano", 
	"Thank you": "Hvala", 
	"We appreciate your patronage. We look forward to your next transaction.": "Hvala za zaupanje. Veselimo se vašega naslednjega obiska."
}